# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.6.0+1.21.7
maven_group=io.github.frqnny
archives_name=mostructures
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.2
# Dependencies
architectury_api_version=17.0.6
fabric_loader_version=0.16.14
fabric_api_version=0.128.2+1.21.7
neoforge_version=21.7.2-beta
yarn_mappings_patch_neoforge_version=1.21+build.4
omega_config_version=1.5.3