# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.6.0+1.21.1
maven_group=io.github.frqnny
archives_name=mostructures
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.17.1
fabric_api_version=0.116.4+1.21.1
neoforge_version=21.1.197
yarn_mappings_patch_neoforge_version=1.21+build.4
omega_config_version=1.5.1