modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/frqnny/mostructures/issues"
license = "LGPL-3.0"

[[mods]]
modId = "mostructures"
version = "${version}"
displayName = "Mo' Structures"
authors = "Frqnny"
description = "Discover exciting structures with fun mini-dungeons and integrated lore!"
logoFile = "assets/mostructures/mostructures.png"

[[dependencies.mostructures]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mostructures]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mostructures]]
modId = "architectury"
type = "required"
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mostructures.mixins.json"
